### ISSUE TITLE
fixed in CCL OSX Mojave

### ISSUE THREAD

**Issue by ijitai** [guicho271828/eazy-gnuplot#39]
easy-gnuplot failed in CCL OSX

> Error: Subprocess with command "gnuplot"
>         exited with error code 127
> While executing: uiop/run-program::%check-result, in process Listener(4).
> Type cmd-/ to continue, cmd-. to abort, cmd-\ for a list of available restarts

But success in SBCL. 

SBCL can find Gnuplot path.
CCL can't find Gnuplot home path.
Add : 

`(setf *GNUPLOT-HOME* "/usr/local/Cellar/gnuplot/5.2.4/bin/gnuplot")`

Codes will work.

**Comment by guicho271828** [comment]
I don't understand what you want to say --- so is it fixed or does it still have a problem?
It looks like somehow CCL runs without the environment variables set properly.
